name: 'Railway Deploy'
description: 'Simple Action to Deploy Railway App using Railway CLI'
inputs:
  railway_token:  # id of input
    description: 'Railway Token for Deployment'
    required: false
outputs:
  status: # id of output
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.railway_token }}
